name: Upload Website

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Prepare Hugo
      uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
      with:
        hugo-version: '0.165.0'
        extended: true
    - name: Build
      run: hugo --gc --minify
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
      with:
        role-to-assume: 'arn:aws:iam::995361647121:role/S3Access'
        aws-region: 'eu-west-1'
    - name: publish
      run: |
        aws s3 sync public s3://svpsouthruislip.org.uk --acl public-read --follow-symlinks --delete
