name: Upload Website

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Prepare Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: '0.165.0'
        extended: true
    - name: Build
      run: hugo --gc --minify
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: 'arn:aws:iam::995361647121:role/S3Access'
        aws-region: 'eu-west-1'
    - name: publish
      run: |
        aws s3 sync public s3://svpsouthruislip.org.uk --acl public-read --follow-symlinks --delete
