name: Upload Website

on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@master
    - name: Prepare Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Prepare Clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: latest
    - name: Build
      run: clojure -M:build
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@main
      with:
        role-to-assume: 'arn:aws:iam::995361647121:role/S3Access'
        aws-region: 'eu-west-1'
    - name: publish
      run: |
        aws s3 sync public s3://svpsouthruislip.org.uk --acl public-read --follow-symlinks --delete
